on:
  push:
    branches:
      - main
    paths:
      - '**.webp'
  workflow_dispatch:  # Add this to allow manual runs


name: Purge jsDelivr Cache

on:
  push:
    branches:
      - main
    paths:
      - '**.webp'

jobs:
  purge:
    name: Purge CDN Cache
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Purge jsDelivr Cache for Updated .webp Files
        run: |
          echo "Looking for updated .webp files..."
          FILES=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep '.webp' || true)
          
          for file in $FILES; do
            echo "Purging: $file"
            curl -X POST "https://purge.jsdelivr.net/gh/jerrycharlton/Creports@main/$file"
          done
